services:
  crawler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ifood_crawler
    working_dir: /app
    shm_size: '2gb'
    stdin_open: true
    tty: true
    command: >
      sh -c "env -u DISPLAY -u XDG_SESSION_TYPE -u WAYLAND_DISPLAY xvfb-run --server-args='-screen 0 1280x900x24 -ac -nolisten tcp -nocursor' poetry run scrapy crawl ifood 2>&1 | tee execucao.log"
    volumes:
      - .:/app:cached
      - /root/.cache     
    environment:
      - PYTHONUNBUFFERED=1
    restart: 'no'